# Generated by Django 4.0.3 on 2022-04-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('brand', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Gigabyte'), (2, 'Asus')], default=0)),
                ('model', models.IntegerField(choices=[(0, 'No value'), (1, '1660super'), (2, 'rx6800xt'), (3, '3070'), (4, '3070lhr'), (5, '3070ti')], default=0)),
                ('memory', models.CharField(max_length=200, null=True)),
                ('memory_manifacturer', models.CharField(max_length=200, null=True)),
                ('wattage', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('pcie_slots', models.IntegerField()),
                ('cpu_chip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hashrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.coin')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.gpu')),
            ],
        ),
    ]
