# Generated by Django 4.0.3 on 2022-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_miningapp', '0002_alter_coin_id_alter_gpu_id_alter_hashrate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.SlugField(default=10, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='slug',
            field=models.SlugField(default=10, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashrate',
            name='slug',
            field=models.SlugField(default=10, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='slug',
            field=models.SlugField(default=10, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
