# Generated by Django 4.0.3 on 2022-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_miningapp', '0003_coin_slug_gpu_slug_hashrate_slug_motherboard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiningRig',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCenter',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Overclock',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('memory_oveclock', models.CharField(blank=True, max_length=200)),
                ('core_overclock', models.CharField(blank=True, max_length=200)),
                ('core_voltage', models.CharField(blank=True, max_length=200)),
                ('memory_controller_voltage', models.CharField(blank=True, max_length=200)),
                ('memory_voltage', models.CharField(blank=True, max_length=200)),
                ('power_limit', models.CharField(blank=True, max_length=200)),
                ('soc_frequency', models.CharField(blank=True, max_length=200)),
                ('soc_vddmax', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitabilityExperiment',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitabilityForecast',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wattage',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memory_manifacturer',
        ),
        migrations.AddField(
            model_name='coin',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_slots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hashrate',
            name='coin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.coin'),
        ),
        migrations.AlterField(
            model_name='hashrate',
            name='gpu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.gpu'),
        ),
        migrations.AlterField(
            model_name='hashrate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='cpu_chip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='RigCase',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('width', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=200)),
                ('length', models.CharField(blank=True, max_length=200)),
                ('open_air', models.BooleanField()),
                ('used_in_rig', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('capacity', models.CharField(blank=True, max_length=200)),
                ('used_in_rig', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('wattage', models.CharField(blank=True, max_length=200)),
                ('efficiency', models.CharField(blank=True, max_length=200)),
                ('noise', models.CharField(blank=True, max_length=200)),
                ('used_in_rig', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('shop', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('locale', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.locale')),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('rpm', models.CharField(blank=True, max_length=200)),
                ('wattage', models.CharField(blank=True, max_length=200)),
                ('noise', models.CharField(blank=True, max_length=200)),
                ('width', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=200)),
                ('length', models.CharField(blank=True, max_length=200)),
                ('used_in_rig', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('chip_manufacturer', models.CharField(blank=True, max_length=200)),
                ('chipset', models.CharField(blank=True, max_length=200)),
                ('core_clock', models.CharField(blank=True, max_length=200)),
                ('used_in_rig', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='live_price',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='live_price',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='overclock',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.overclock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='used_in_rig',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.miningrig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpu',
            name='wattage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.wattage'),
        ),
    ]
