# Generated by Django 4.0.3 on 2022-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_miningapp', '0005_alter_coin_currency_alter_coin_live_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hashrate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locale',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='miningrig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='operationcenter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='overclock',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profitabilityexperiment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profitabilityforecast',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rigcase',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wattage',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='coin',
            table='coin',
        ),
        migrations.AlterModelTable(
            name='cpu',
            table='cpu',
        ),
        migrations.AlterModelTable(
            name='fan',
            table='fan',
        ),
        migrations.AlterModelTable(
            name='gpu',
            table='gpu',
        ),
        migrations.AlterModelTable(
            name='hashrate',
            table='hashrate',
        ),
        migrations.AlterModelTable(
            name='locale',
            table='locale',
        ),
        migrations.AlterModelTable(
            name='miningrig',
            table='miningrig',
        ),
        migrations.AlterModelTable(
            name='motherboard',
            table='motherboard',
        ),
        migrations.AlterModelTable(
            name='operationcenter',
            table='operationcenter',
        ),
        migrations.AlterModelTable(
            name='overclock',
            table='overclock',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
        migrations.AlterModelTable(
            name='profitabilityexperiment',
            table='profitabilityexperiment',
        ),
        migrations.AlterModelTable(
            name='profitabilityforecast',
            table='profitabilityforecast',
        ),
        migrations.AlterModelTable(
            name='psu',
            table='psu',
        ),
        migrations.AlterModelTable(
            name='ram',
            table='ram',
        ),
        migrations.AlterModelTable(
            name='rigcase',
            table='rigcase',
        ),
        migrations.AlterModelTable(
            name='wattage',
            table='wattage',
        ),
    ]
