# Generated by Django 4.0.3 on 2022-04-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_miningapp', '0006_alter_coin_options_alter_cpu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='live_price',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.price'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='overclock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.overclock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='wattage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_miningapp.wattage'),
        ),
    ]
